HTMLElement.prototype.wrap=function(e){this.parentNode.insertBefore(e,this),this.parentNode.removeChild(this),e.appendChild(this)},Fluid.events={registerNavbarEvent:function(){var e,t=jQuery("#navbar");0!==t.length&&(e=jQuery("#navbar .dropdown-menu"),0<t.offset().top&&(t.removeClass("navbar-dark"),e.removeClass("navbar-dark")),Fluid.utils.listenScroll(function(){t[50<t.offset().top?"addClass":"removeClass"]("top-nav-collapse"),e[50<t.offset().top?"addClass":"removeClass"]("dropdown-collapse"),0<t.offset().top?t.removeClass("navbar-dark"):t.addClass("navbar-dark"),e.removeClass("navbar-dark")}),jQuery("#navbar-toggler-btn").on("click",function(){jQuery(".animated-icon").toggleClass("open"),jQuery("#navbar").toggleClass("navbar-col-show")}))},registerParallaxEvent:function(){var a,n=jQuery('#banner[parallax="true"]');0!==n.length&&0!==(a=jQuery("#board")).length&&Fluid.utils.listenScroll(function(){var e=jQuery(window).scrollTop()/5,t=96+parseInt(a.css("margin-top"),10),t=(n.css({transform:"translate3d(0,"+(e=t<e?t:e)+"px,0)"}),jQuery(".side-col"));t&&t.css({"padding-top":e+"px"})})},registerScrollDownArrowEvent:function(){var e=jQuery(".scroll-down-bar");0!==e.length&&e.on("click",function(){Fluid.utils.scrollToElement("#board",-jQuery("#navbar").height())})},registerScrollTopArrowEvent:function(){var t,a,n,e,r,o=jQuery("#scroll-top-button");0!==o.length&&0!==(t=jQuery("#board")).length&&(n=a=!1,(e=function(){var e=t[0].getClientRects()[0].right,e=document.body.offsetWidth-e;a=50<=e,o.css({bottom:a&&n?"20px":"-60px",right:e-64+"px"})})(),jQuery(window).resize(e),r=t.offset().top,Fluid.utils.listenScroll(function(){var e=document.body.scrollTop+document.documentElement.scrollTop;n=r<=e,o.css({bottom:a&&n?"20px":"-60px"})}),o.on("click",function(){jQuery("body,html").animate({scrollTop:0,easing:"swing"})}))},registerImageLoadedEvent:function(){if("NProgress"in window){var e,a=document.getElementById("banner"),a=(a&&(a=a.style.backgroundImage.match(/\((.*?)\)/)[1].replace(/(['"])/g,""),(e=new Image).onload=function(){window.NProgress&&window.NProgress.inc(.2)},e.src=a,e.complete)&&e.onload(),jQuery("main img:not([lazyload])")),n=a.length;for(let t of a){let e=t.onload;t.onload=function(){e&&e(),window.NProgress&&window.NProgress.inc(.5/n)},t.complete&&t.onload()}}},registerRefreshCallback:function(e){Array.isArray(Fluid.events._refreshCallbacks)||(Fluid.events._refreshCallbacks=[]),Fluid.events._refreshCallbacks.push(e)},refresh:function(){if(Array.isArray(Fluid.events._refreshCallbacks))for(var e of Fluid.events._refreshCallbacks)e instanceof Function&&e()},billboard:function(){"console"in window&&console.log(`
------------------------------------------------
|                                              |
|     ________  __            _        __      |
|    |_   __  |[  |          (_)      |  ]     |
|      | |_ \\_| | | __   _   __   .--.| |      |
|      |  _|    | |[  | | | [  |/ /'\`\\' |      |
|     _| |_     | | | \\_/ |, | || \\__/  |      |
|    |_____|   [___]'.__.'_/[___]'.__.;__]     |
|                                              |
|           Powered by Hexo x Fluid            |
|         GitHub: https://git.io/JqpVD         |
|                                              |
------------------------------------------------
    `)}},HTMLElement.prototype.wrap=function(e){this.parentNode.insertBefore(e,this),this.parentNode.removeChild(this),e.appendChild(this)},Fluid.plugins={typing:function(e){var t;"Typed"in window&&((t=new window.Typed("#subtitle",{strings:["  ",e],cursorChar:CONFIG.typing.cursorChar,typeSpeed:CONFIG.typing.typeSpeed,loop:CONFIG.typing.loop})).stop(),(e=document.getElementById("subtitle"))&&(e.innerText=""),jQuery(document).ready(function(){t.start()}))},fancyBox:function(e){CONFIG.image_zoom.enable&&"fancybox"in jQuery&&(jQuery(e||".markdown-body :not(a) > img, .markdown-body > img").each(function(){var e,t,a=jQuery(this),n=a.attr("data-src")||a.attr("src")||"",r=(CONFIG.image_zoom.img_url_replace&&(t=(e=CONFIG.image_zoom.img_url_replace)[0]||"",e=e[1]||"",t)&&(n=/^re:/.test(t)?(t=t.replace(/^re:/,""),r=new RegExp(t,"gi"),n.replace(r,e)):n.replace(t,e)),a.wrap(`
        <a class="fancybox fancybox.image" href="${n}"
          itemscope itemtype="http://schema.org/ImageObject" itemprop="url"></a>`).parent("a"));0!==r.length&&(a.is(".group-image-container img")?r.attr("data-fancybox","group").attr("rel","group"):r.attr("data-fancybox","default").attr("rel","default"),t=a.attr("title")||a.attr("alt"))&&r.attr("title",t).attr("data-caption",t)}),jQuery.fancybox.defaults.hash=!1,jQuery(".fancybox").fancybox({loop:!0,helpers:{overlay:{locked:!1}}}))},imageCaption:function(e){CONFIG.image_caption.enable&&jQuery(e||`.markdown-body > p > img, .markdown-body > figure > img,
      .markdown-body > p > a.fancybox, .markdown-body > figure > a.fancybox`).each(function(){var e=jQuery(this),t=e.next("figcaption");0!==t.length?t.addClass("image-caption"):(t=e.attr("title")||e.attr("alt"))&&e.after(`<figcaption aria-hidden="true" class="image-caption">${t}</figcaption>`)})},codeWidget(){var a,n=CONFIG.code_language.enable&&CONFIG.code_language.default,r=CONFIG.copy_btn&&"ClipboardJS"in window;(n||r)&&(a="",a+='<div class="code-widget">LANG</div>',jQuery(".markdown-body pre").each(function(){var e,t=jQuery(this);0<t.find("code.mermaid").length||0<t.find("span.line").length||(e="",n&&(e=CONFIG.code_language.default,0<t[0].children.length&&2<=t[0].children[0].classList.length&&t.children().hasClass("hljs")?e=t[0].children[0].classList[1]:t[0].getAttribute("data-language")?e=t[0].getAttribute("data-language"):t.parent().hasClass("sourceCode")&&0<t[0].children.length&&2<=t[0].children[0].classList.length?(e=t[0].children[0].classList[1],t.parent().addClass("code-wrapper")):t.parent().hasClass("markdown-body")&&0===t[0].classList.length&&t.wrap('<div class="code-wrapper"></div>'),e=e.toUpperCase().replace("NONE",CONFIG.code_language.default)),t.append(a.replace("LANG",e).replace('code-widget">',(e=t[0],(0<=Fluid.utils.getBackgroundLightness(e)?"code-widget-light":"code-widget-dark")+(r?' code-widget copy-btn" data-clipboard-snippet><i class="iconfont icon-copy"></i>':' code-widget">')))),r&&new ClipboardJS(".copy-btn",{target:function(e){for(var t=e.parentNode.childNodes,a=0;a<t.length;a++)if("CODE"===t[a].tagName)return t[a]}}).on("success",function(e){e.clearSelection(),e.trigger.innerHTML=e.trigger.innerHTML.replace("icon-copy","icon-success"),setTimeout(function(){e.trigger.innerHTML=e.trigger.innerHTML.replace("icon-success","icon-copy")},2e3)}))}))}};